package com.fiqhsearcher.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF006684)
val light_onPrimary = Color(0xFFffffff)
val light_primaryContainer = Color(0xFFbae9ff)
val light_onPrimaryContainer = Color(0xFF001f2a)
val light_secondary = Color(0xFF4d616b)
val light_onSecondary = Color(0xFFffffff)
val light_secondaryContainer = Color(0xFFd0e6f2)
val light_onSecondaryContainer = Color(0xFF081e27)
val light_tertiary = Color(0xFF5d5b7e)
val light_onTertiary = Color(0xFFffffff)
val light_tertiaryContainer = Color(0xFFe3dfff)
val light_onTertiaryContainer = Color(0xFF191836)
val light_error = Color(0xFFba1b1b)
val light_errorContainer = Color(0xFFffdad4)
val light_onError = Color(0xFFffffff)
val light_onErrorContainer = Color(0xFF410001)
val light_background = Color(0xFFfbfcfe)
val light_onBackground = Color(0xFF191c1e)
val light_surface = Color(0xFFfbfcfe)
val light_onSurface = Color(0xFF191c1e)
val light_surfaceVariant = Color(0xFFdce3e8)
val light_onSurfaceVariant = Color(0xFF40484c)
val light_outline = Color(0xFF70787d)
val light_inverseOnSurface = Color(0xFFf0f1f3)
val light_inverseSurface = Color(0xFF2e3133)
val light_inversePrimary = Color(0xFF63d3ff)
val light_shadow = Color(0xFF000000)

val dark_primary = Color(0xFF63d3ff)
val dark_onPrimary = Color(0xFF003546)
val dark_primaryContainer = Color(0xFF004d65)
val dark_onPrimaryContainer = Color(0xFFbae9ff)
val dark_secondary = Color(0xFFb4cad6)
val dark_onSecondary = Color(0xFF1f333c)
val dark_secondaryContainer = Color(0xFF354a54)
val dark_onSecondaryContainer = Color(0xFFd0e6f2)
val dark_tertiary = Color(0xFFc6c3ea)
val dark_onTertiary = Color(0xFF2e2d4c)
val dark_tertiaryContainer = Color(0xFF454365)
val dark_onTertiaryContainer = Color(0xFFe3dfff)
val dark_error = Color(0xFFffb4a9)
val dark_errorContainer = Color(0xFF930006)
val dark_onError = Color(0xFF680003)
val dark_onErrorContainer = Color(0xFFffdad4)
val dark_background = Color(0xFF191c1e)
val dark_onBackground = Color(0xFFe1e2e4)
val dark_surface = Color(0xFF191c1e)
val dark_onSurface = Color(0xFFe1e2e4)
val dark_surfaceVariant = Color(0xFF40484c)
val dark_onSurfaceVariant = Color(0xFFc0c8cd)
val dark_outline = Color(0xFF8a9296)
val dark_inverseOnSurface = Color(0xFF191c1e)
val dark_inverseSurface = Color(0xFFe1e2e4)
val dark_inversePrimary = Color(0xFF006684)
val dark_shadow = Color(0xFF000000)

val seed = Color(0xFF518ba4)
val error = Color(0xFFba1b1b)